# Generated by Django 6.0.7 on 2026-07-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/images/'),
        ),
        migrations.AddField(
            model_name='historicalcatalog',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
