# Generated by Django 6.0.7 on 2026-07-18 11:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalog_image_historicalcatalog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcatalog',
            name='name',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalog',
            name='category',
            field=models.CharField(blank=True, choices=[('landscapes', 'Landscapes'), ('portraits', 'Portraits'), ('mixed_media', 'Mixed Media'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcatalog',
            name='category',
            field=models.CharField(blank=True, choices=[('landscapes', 'Landscapes'), ('portraits', 'Portraits'), ('mixed_media', 'Mixed Media'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
