# Generated by Django 6.0.7 on 2026-07-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_catalog_medium_catalog_year_historicalcatalog_medium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalcatalog',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
