# Generated by Django 6.0.7 on 2026-07-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_catalog_is_sold_historicalcatalog_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalcatalog',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
