# Generated by Django 6.0.7 on 2026-07-20 14:55

import django.db.models.deletion
import inquiries.managers
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalInquiry',
            fields=[
                ('inquiry_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('inquirer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('inquirer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('inquirer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('catalog', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.catalog')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical inquiry',
                'verbose_name_plural': 'historical inquirys',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('inquiry_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inquirer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('inquirer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('inquirer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='catalog.catalog')),
            ],
            options={
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', inquiries.managers.InquiryManager()),
            ],
        ),
    ]
