# Generated by Django 6.0.7 on 2026-07-17 01:18

import users.managers
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('telephone_number', models.CharField(blank=True, db_index=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_staff', models.BooleanField(db_index=True, default=False)),
                ('is_superuser', models.BooleanField(db_index=True, default=False)),
                ('is_soft_deleted', models.BooleanField(db_index=True, default=False)),
                ('soft_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, null=True)),
                ('password_expires_in_days', models.PositiveIntegerField(default=90)),
                ('session_version', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('can_soft_delete_user', 'Can soft delete a user'), ('can_deactivate_user', 'Can deactivate a user'), ('can_activate_user', 'Can activate a user')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_soft_deleted', False)), fields=('telephone_number',), name='unique_active_telephone_number')],
            },
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
    ]
