# Generated by Django 6.0.7 on 2026-07-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_expires_in_days',
        ),
    ]
